# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_auto_20180713_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_authors',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books_authors',
            name='book',
        ),
        migrations.AddField(
            model_name='author',
            name='book_authors',
            field=models.ManyToManyField(related_name='books', to='book_authors.Book'),
        ),
        migrations.DeleteModel(
            name='books_authors',
        ),
    ]
