# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-14 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0004_auto_20180713_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='text',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
